name: Technical Interview Review
on:
  pull_request:
    types: [opened]

jobs:
  technical-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate Github App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Review code submission
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ steps.app-token.outputs.token }}
          direct_prompt: ${{ vars.BACKEND_INTERVIEW_PROMPT }}
          allowed_tools: |
            Bash(cd*)
            Bash(grep*)
            Bash(ls*)
            Bash(pwd*)
            Bash(echo*)
            Bash(cat*)
            Bash(find*)
            Bash(git log*)
            Bash(git show*)
            Bash(git diff*)
            Bash(git status*)
            Bash(pip*)
            Bash(python*)
            Bash(pytest*)
            Bash(docker*)
            Bash(head*)
            Bash(tail*)
            Bash(wc*)
            Bash(sort*)
            Bash(uniq*)
            Glob
            Grep
            LS
            Read
            WebSearch

# TODO: Print output in Pull Request (confirm working)
# TODO: Create note in Ashby and tag @Colton Rhyason
