name: Technical Interview Review
on:
  pull_request:
    types: [opened]

jobs:
  technical-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      CANDIDATE_ID: ${{ github.event.pull_request.body }}
      REPOSITORY: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.number }}
      ASHBY_API_KEY: ${{ secrets.ASHBY_API_KEY }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      TO_EMAIL: thabang@textlayer.ai
      FROM_EMAIL: services@textlayer.ai
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate Github App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Review code submission
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ steps.app-token.outputs.token }}
          direct_prompt: ${{ vars.BACKEND_INTERVIEW_PROMPT }}
          allowed_tools: |
            Bash(cd*)
            Bash(grep*)
            Bash(ls*)
            Bash(pwd*)
            Bash(echo*)
            Bash(cat*)
            Bash(find*)
            Bash(git log*)
            Bash(git show*)
            Bash(git diff*)
            Bash(git status*)
            Bash(pip*)
            Bash(python*)
            Bash(pytest*)
            Bash(docker*)
            Bash(head*)
            Bash(tail*)
            Bash(wc*)
            Bash(sort*)
            Bash(uniq*)
            Glob
            Grep
            LS
            Read
            WebSearch

      - name: Create Ashby note
        run: |
          curl --request POST \
               --url https://api.ashbyhq.com/candidate.createNote \
               -u $ASHBY_API_KEY: \
               --header 'accept: application/json; version=1' \
               --header 'content-type: application/json' \
               --data '{
                 "sendNotifications": true,
                 "candidateId": "'$CANDIDATE_ID'",
                 "note": "Technical review completed. You can find the feedback here: https://github.com/'$REPOSITORY'/pull/'$PR_NUMBER'"
               }'

      - name: Get candidate info from Ashby
        id: candidate-info
        run: |
          response=$(curl --request POST \
                          --url https://api.ashbyhq.com/candidate.info \
                          -u $ASHBY_API_KEY: \
                          --header 'accept: application/json; version=1' \
                          --header 'content-type: application/json' \
                          --data '{
                            "id": "'$CANDIDATE_ID'"
                          }')
          
          application_id=$(echo "$response" | jq -r '.results.applicationIds[0]')
          echo "application_id=$application_id" >> $GITHUB_OUTPUT

      - name: Send email notification
        run: |
          curl --request POST \
               --url https://api.sendgrid.com/v3/mail/send \
               --header 'Authorization: Bearer '$SENDGRID_API_KEY'' \
               --header 'Content-Type: application/json' \
               --data '{
                 "personalizations": [
                   {
                     "to": [
                       {
                         "email": "'$TO_EMAIL'"
                       }
                     ],
                     "subject": "Application note has been added"
                   }
                 ],
                 "from": {
                   "email": "'$FROM_EMAIL'"
                 },
                 "content": [
                   {
                     "type": "text/plain",
                     "value": "Application note has been added: https://app.ashbyhq.com/candidates/pipeline/active/right-side/candidates/'$CANDIDATE_ID'/applications/${{ steps.candidate-info.outputs.application_id }}/feed"
                   }
                 ]
               }'
